sudo: required
language: scala

dist: xenial

scala:
  - 2.12.8

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk:
  - openjdk8

jobs:
  include:
    - stage: Test
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: Deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: heroku-t-christopherdavenport
        api_key: $HEROKU_AUTH_TOKEN